name: 'Find new CVEs'
description: |
  Check if there is a new CVE per each dependency

inputs:
  db_uri:
    description: Database URI
    required: true
  webhook_url:
    description: Slack Webhook URL
    required: true

runs:
  using: 'composite'
  steps:
    - id: find-new-cves
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        cd "${{ github.action_path }}/entrypoint"

        go build -o ./entrypoint

        ./entrypoint \
          --db-uri "${{ inputs.db_uri }}" \
          --webhook-url "${{ inputs.webhook_url }}"

        rm -f ./entrypoint