name: 'Update Tracked CVEs'
description: |
  Check if the file tracking the CVEs have any update. Add/Remove tracked dependencies if neccesary

inputs:
  db_uri:
    description: Database URI
    required: true

runs:
  using: 'composite'
  steps:
    - id: update-tracked-deps
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euo pipefail

        cd "${{ github.action_path }}/entrypoint"

        go build -o ./entrypoint

        ./entrypoint \
          --db-uri "${{ inputs.db_uri }}" \
          --dep-list "${{ github.workspace }}/dependencies.csv"

        rm -f ./entrypoint