name: Find new CVEs

"on":
  workflow_dispatch: { }
##  schedule:
##    - cron: '0 */2 * * *'

env:
  DB_URI: ${{ secrets.DB_URI }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  check-cves:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Find new CVEs
        id: find-new-cves
        uses: brayanhenao/cve-notification-app/actions/find-new-cves@main
        with:
          db_uri: ${{ env.DB_URI }}
          webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
